//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miseng.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miseng.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   body{
        ///	
        ///}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string basicCSS {
            get {
                return ResourceManager.GetString("basicCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no&quot;&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;    
        ///    &lt;title&gt;test&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;lib/tau/wearable/theme/default/tau.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;./css/style.css&quot;/&gt;
        ///    &lt;script src=&quot;./lib/tau/wearable/js/tau.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;./js/core/core.js&quot; data-main=&quot;./js/app.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string basicHtml {
            get {
                return ResourceManager.GetString("basicHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /* js File */과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string basicJS {
            get {
                return ResourceManager.GetString("basicJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Images/diskdrive.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Drive_Image_Path {
            get {
                return ResourceManager.GetString("Drive_Image_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Images/file.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Image_Path {
            get {
                return ResourceManager.GetString("File_Image_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Images/folder.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Folder_Image_Path {
            get {
                return ResourceManager.GetString("Folder_Image_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WorkSpace(Projects)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string My_WorkSpace {
            get {
                return ResourceManager.GetString("My_WorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MisengWorkSpace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string My_WorkSpace_Name {
            get {
                return ResourceManager.GetString("My_WorkSpace_Name", resourceCulture);
            }
        }
    }
}
